Updated restart to not require sudo permissions and updated bupServ to handle directories that do not exist.

diff --git a/bupServ b/bupServ
--- a/bupServ
+++ b/bupServ
@@ -34,12 +34,11 @@ function backupServer() {
         echo "Copying from $currPath."
         mkdir -p $BUPPATH$currPath > /dev/null 2>&1 #Make the directory path on the backup-side (if it's not already present)
         rsync -qr $USER@$SERVER:$currPath/* $BUPPATH$currPath > /dev/null 2>&1 #Copy the directory
-        if [ $? != 0 ] && [ $? != 23 ]; then #Sets the error code for any error aside from File IO
-          exitCode=$?
-        elif [ $? == 23 ]; then #Sets the error code for File IO
-          exitCode=$?
+        local exit=$? #Saving the exit code right after the rsync is called so that it can't be changed by other methods.
+        if [ $exit != 0 ]; then #Sets the error code if unsuccessful
+          exitCode=$exit
         fi
-      done < "$1" #Piped out of the file in the first parameter
+      done < "$1" #Input piped out of the file in the first parameter
     else
       echo "Copying all files within permissions."
       rsync -qr $USER@$SERVER:/ $BUPPATH > /dev/null 2>&1 #If no input file is given, attempt to back up the entire server.
@@ -49,7 +48,7 @@ function backupServer() {
       echo "Backup completed!"
       exit 0 
     elif [ $exitCode == 23 ]; then #If an IO File error occurred (like denied privacy), but no other has occurred.
-        echo "All files in your permissions are backed up, but there were some files outside of your permissions that could not be copied."
+        echo "All files that exist within your permissions were backed up."
         exit 1
     else #If anything other than an IO File error occurred
       echo "An error occurred during the backup, and the backup may be incomplete."
