Changed update to work properly again, didn't work without sudo permissions. Updated comments on a lot of files and added exit codes to some files.

diff --git a/restart b/restart
--- a/restart
+++ b/restart
@@ -1,4 +1,11 @@
 #!/bin/bash
+#Ryan Houck
+#Last updated on April 16, 2018
+#Queries to restart the computer
+
+#EXIT CODES:
+ #0: No errors
+ #1: User authentification failed.
 
 echo "Do you want to restart? Please respond with [y/N]."
 read input
@@ -7,8 +14,15 @@ while [ "$input" != "y" ] && [ "$input" != "n" ] && [ "$input" != "Y" ] && [ "$i
   read input
 done
 if [ "$input" == "y" ] || [ "$input" == "Y" ]; then
-  shutdown -r now
-  echo "Restarting."
+  sudo shutdown -r now
+  if [ $? == 0 ]; then
+    echo "Restarting."
+    exit 0
+  else
+    echo "Failed user authentification, restart aborted."
+    exit 1
+  fi
 else
   echo "Restart aborted."
+  exit 0
 fi
diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,18 +1,34 @@
 #!/bin/bash
+#Ryan Houck
+#Last updated on April 16, 2018
+#Checks for updates, then gives the user to update and/or
+#restart if there is an update.
+
+#EXIT CODES:
+ #0: No errors
+ #1: An error occurred while checking for updates
+ #2: An error occurred while updating
+
 function updateFunc() {
   echo "Checking for updates..."
-  sudo dnf check-update > /dev/null
+  sudo dnf check-update > /dev/null 2>&1
   local checkUpdate=$?
   if test 0 -eq $checkUpdate; then
     echo "No updates available!"
+    exit 0
   fi
   if test 1 -eq $checkUpdate; then
-    echo "An error occured!"
+    echo "An error occured checking for updates!"
+    exit 1
   fi
   if test 100 -eq $checkUpdate; then
     sudo dnf update
     if test 0 -eq $?; then
       restart
+      exit 0
+    else
+      echo "An error occurred during the update!"
+      exit 2
     fi
   fi
 }
